import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  // GitHub Actions ubuntu-latest: 4 vCPUs; local dev: tune to your machine
  workers: process.env.E2E_WORKERS ? parseInt(process.env.E2E_WORKERS, 10) : (process.env.CI ? 3 : 8),
  reporter: process.env.CI ? 'github' : 'list',

  use: {
    headless: true,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },

  timeout: 30000,
  expect: {
    timeout: 10000,
  },

  // Only match spec files, not helper files
  testMatch: '**/*.spec.js',
});

// ---- live-validation filler block (throwaway PR, do not merge) ----
// live-validation filler line 1
// live-validation filler line 2
// live-validation filler line 3
// live-validation filler line 4
// live-validation filler line 5
// live-validation filler line 6
// live-validation filler line 7
// live-validation filler line 8
// live-validation filler line 9
// live-validation filler line 10
// live-validation filler line 11
// live-validation filler line 12
// live-validation filler line 13
// live-validation filler line 14
// live-validation filler line 15
// live-validation filler line 16
// live-validation filler line 17
// live-validation filler line 18
// live-validation filler line 19
// live-validation filler line 20
// live-validation filler line 21
// live-validation filler line 22
// live-validation filler line 23
// live-validation filler line 24
// live-validation filler line 25
// live-validation filler line 26
// live-validation filler line 27
// live-validation filler line 28
// live-validation filler line 29
// live-validation filler line 30
// live-validation filler line 31
// live-validation filler line 32
// live-validation filler line 33
// live-validation filler line 34
// live-validation filler line 35
// live-validation filler line 36
// live-validation filler line 37
// live-validation filler line 38
// live-validation filler line 39
// live-validation filler line 40
// live-validation filler line 41
// live-validation filler line 42
// live-validation filler line 43
// live-validation filler line 44
// live-validation filler line 45
// live-validation filler line 46
// live-validation filler line 47
// live-validation filler line 48
// live-validation filler line 49
// live-validation filler line 50
// live-validation filler line 51
// live-validation filler line 52
// live-validation filler line 53
// live-validation filler line 54
// live-validation filler line 55
// live-validation filler line 56
// live-validation filler line 57
// live-validation filler line 58
// live-validation filler line 59
// live-validation filler line 60
// live-validation filler line 61
// live-validation filler line 62
// live-validation filler line 63
// live-validation filler line 64
// live-validation filler line 65
// live-validation filler line 66
// live-validation filler line 67
// live-validation filler line 68
// live-validation filler line 69
// live-validation filler line 70
// live-validation filler line 71
// live-validation filler line 72
// live-validation filler line 73
// live-validation filler line 74
// live-validation filler line 75
// live-validation filler line 76
// live-validation filler line 77
// live-validation filler line 78
// live-validation filler line 79
// live-validation filler line 80
// live-validation filler line 81
// live-validation filler line 82
// live-validation filler line 83
// live-validation filler line 84
// live-validation filler line 85
// live-validation filler line 86
// live-validation filler line 87
// live-validation filler line 88
// live-validation filler line 89
// live-validation filler line 90
// live-validation filler line 91
// live-validation filler line 92
// live-validation filler line 93
// live-validation filler line 94
// live-validation filler line 95
// live-validation filler line 96
// live-validation filler line 97
// live-validation filler line 98
// live-validation filler line 99
// live-validation filler line 100
// live-validation filler line 101
// live-validation filler line 102
// live-validation filler line 103
// live-validation filler line 104
// live-validation filler line 105
// live-validation filler line 106
// live-validation filler line 107
// live-validation filler line 108
// live-validation filler line 109
// live-validation filler line 110
// live-validation filler line 111
// live-validation filler line 112
// live-validation filler line 113
// live-validation filler line 114
// live-validation filler line 115
// live-validation filler line 116
// live-validation filler line 117
// live-validation filler line 118
// live-validation filler line 119
// live-validation filler line 120
// live-validation filler line 121
// live-validation filler line 122
// live-validation filler line 123
// live-validation filler line 124
// live-validation filler line 125
// live-validation filler line 126
// live-validation filler line 127
// live-validation filler line 128
// live-validation filler line 129
// live-validation filler line 130
// live-validation filler line 131
// live-validation filler line 132
// live-validation filler line 133
// live-validation filler line 134
// live-validation filler line 135
// live-validation filler line 136
// live-validation filler line 137
// live-validation filler line 138
// live-validation filler line 139
// live-validation filler line 140
// live-validation filler line 141
// live-validation filler line 142
// live-validation filler line 143
// live-validation filler line 144
// live-validation filler line 145
// live-validation filler line 146
// live-validation filler line 147
// live-validation filler line 148
// live-validation filler line 149
// live-validation filler line 150
// live-validation filler line 151
// live-validation filler line 152
// live-validation filler line 153
// live-validation filler line 154
// live-validation filler line 155
// live-validation filler line 156
// live-validation filler line 157
// live-validation filler line 158
// live-validation filler line 159
// live-validation filler line 160
// live-validation filler line 161
// live-validation filler line 162
// live-validation filler line 163
// live-validation filler line 164
// live-validation filler line 165
// live-validation filler line 166
// live-validation filler line 167
// live-validation filler line 168
// live-validation filler line 169
// live-validation filler line 170
// live-validation filler line 171
// live-validation filler line 172
// live-validation filler line 173
// live-validation filler line 174
// live-validation filler line 175
// live-validation filler line 176
// live-validation filler line 177
// live-validation filler line 178
// live-validation filler line 179
// live-validation filler line 180
// live-validation filler line 181
// live-validation filler line 182
// live-validation filler line 183
// live-validation filler line 184
// live-validation filler line 185
// live-validation filler line 186
// live-validation filler line 187
// live-validation filler line 188
// live-validation filler line 189
// live-validation filler line 190
// live-validation filler line 191
// live-validation filler line 192
// live-validation filler line 193
// live-validation filler line 194
// live-validation filler line 195
// live-validation filler line 196
// live-validation filler line 197
// live-validation filler line 198
// live-validation filler line 199
// live-validation filler line 200
// live-validation filler line 201
// live-validation filler line 202
// live-validation filler line 203
// live-validation filler line 204
// live-validation filler line 205
// live-validation filler line 206
// live-validation filler line 207
// live-validation filler line 208
// live-validation filler line 209
// live-validation filler line 210
// live-validation filler line 211
// live-validation filler line 212
// live-validation filler line 213
// live-validation filler line 214
// live-validation filler line 215
// live-validation filler line 216
// live-validation filler line 217
// live-validation filler line 218
// live-validation filler line 219
// live-validation filler line 220
// live-validation filler line 221
// live-validation filler line 222
// live-validation filler line 223
// live-validation filler line 224
// live-validation filler line 225
// live-validation filler line 226
// live-validation filler line 227
// live-validation filler line 228
// live-validation filler line 229
// live-validation filler line 230
// live-validation filler line 231
// live-validation filler line 232
// live-validation filler line 233
// live-validation filler line 234
// live-validation filler line 235
// live-validation filler line 236
// live-validation filler line 237
// live-validation filler line 238
// live-validation filler line 239
// live-validation filler line 240
// live-validation filler line 241
// live-validation filler line 242
// live-validation filler line 243
// live-validation filler line 244
// live-validation filler line 245
// live-validation filler line 246
// live-validation filler line 247
// live-validation filler line 248
// live-validation filler line 249
// live-validation filler line 250
// live-validation filler line 251
// live-validation filler line 252
// live-validation filler line 253
// live-validation filler line 254
// live-validation filler line 255
// live-validation filler line 256
// live-validation filler line 257
// live-validation filler line 258
// live-validation filler line 259
// live-validation filler line 260
// live-validation filler line 261
// live-validation filler line 262
// live-validation filler line 263
// live-validation filler line 264
// live-validation filler line 265
// live-validation filler line 266
// live-validation filler line 267
// live-validation filler line 268
// live-validation filler line 269
// live-validation filler line 270
// live-validation filler line 271
// live-validation filler line 272
// live-validation filler line 273
// live-validation filler line 274
// live-validation filler line 275
// live-validation filler line 276
// live-validation filler line 277
// live-validation filler line 278
// live-validation filler line 279
// live-validation filler line 280
// live-validation filler line 281
// live-validation filler line 282
// live-validation filler line 283
// live-validation filler line 284
// live-validation filler line 285
// live-validation filler line 286
// live-validation filler line 287
// live-validation filler line 288
// live-validation filler line 289
// live-validation filler line 290
// live-validation filler line 291
// live-validation filler line 292
// live-validation filler line 293
// live-validation filler line 294
// live-validation filler line 295
// live-validation filler line 296
// live-validation filler line 297
// live-validation filler line 298
// live-validation filler line 299
// live-validation filler line 300
